# Generated by Django 3.1.4 on 2020-12-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_code')),
                ('menu_pdf', models.FileField(blank=True, upload_to='menu')),
            ],
        ),
    ]
