# Generated by Django 3.1.4 on 2021-01-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20210102_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='stripeCustomerId',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='stripeSubscriptionId',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
